[package]
name = "boxingtimer2"
version = "0.1.0"
authors = ["Adrien Pensart <crunchengine@gmail.com>"]
edition = "2021"

[build-dependencies]
dioxus-daisyui = "0.7.0"

[dependencies]
dioxus = { version = "0.5", features = ["web", "router"] }
gloo = { version = "0.11.0", features = ["futures"] }
# log = "0.4.19"
dioxus-logger = "0.5.0"
console_error_panic_hook = "0.1.7"
derive_more = { version = "1.0", features = ["full"] }
js-sys = "0.3.69"
wasm-bindgen-futures = "0.4.42"
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["HtmlAudioElement"] }
duration-string = { version = "0.4.0", features = ["serde"] }
derive_builder = { version = "0.20.0", features = ["clippy"] }
derive-new = "0.6.0"
itertools = "0.13.0"
thiserror = "1.0.63"
manganis = "0.2.2"
